import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import PageHeader from "../../components/layout/PageHeader";
import Button from "../../components/ui/button/Button";
import { useToast } from "../../components/feedback/Toast";
import { listReceipts } from "../../services/booking/installmentPaymentApi.js";
import { formatINR } from "../../utils/format";

function formatDate(value) {
  return value ? new Date(value).toLocaleString("en-IN") : "—";
}

export default function ReceiptList() {
  const navigate = useNavigate();
  const toast = useToast();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);

  const load = () => {
    setLoading(true);
    listReceipts({ pageSize: 100 })
      .then((result) => setItems(result?.items || []))
      .catch((err) => {
        toast.error(err.message || "Failed to load receipts.");
        setItems([]);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  return (
    <motion.div className="erp-module-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
      <PageHeader
        title="Receipts"
        description="Approved payment receipts generated by the production receipt service."
        actions={<Button variant="ghost" size="md" onClick={load}>Refresh</Button>}
      />

      {loading && <p>Loading receipts...</p>}
      {!loading && items.length === 0 && <p>No receipts available yet.</p>}

      <div className="dashboard__table-wrap">
        <table className="dashboard__table">
          <thead>
            <tr>
              <th>Receipt #</th>
              <th>Payment #</th>
              <th>Customer</th>
              <th>Booking</th>
              <th>Property</th>
              <th>Installment</th>
              <th>Amount</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            {items.map((receipt) => (
              <tr key={receipt.id} role="button" tabIndex={0} onClick={() => navigate(`/dashboard/receipts/${receipt.id}`)} onKeyDown={(e) => e.key === "Enter" && navigate(`/dashboard/receipts/${receipt.id}`)}>
                <td>{receipt.receiptNumber}</td>
                <td>{receipt.paymentNumber}</td>
                <td>{receipt.booking?.customerName}</td>
                <td>{receipt.booking?.bookingNumber}</td>
                <td>{receipt.property?.title || "—"}</td>
                <td>{receipt.installmentNumber ?? "—"}</td>
                <td>{formatINR(receipt.amount)}</td>
                <td>{formatDate(receipt.approvedAt || receipt.paidAt)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </motion.div>
  );
}
